<?php

namespace Database\Seeders;

use App\Models\Blog;
use Illuminate\Support\Str;
use Illuminate\Database\Seeder;

class BlogSeeder extends Seeder
{
    public function run(): void
    {
        // Clear existing data
        Blog::truncate();

        $blogEntries = [
            // Blog Category - Career & Professional Development (15 items)
            [
                'judul' => 'Mengapa Sertifikasi Profesional Penting di Era Digital',
                'konten' => 'Di era digital yang terus berkembang pesat, sertifikasi profesional menjadi kunci utama untuk meningkatkan kredibilitas dan daya saing di dunia kerja. Artikel ini membahas berbagai manfaat sertifikasi dan bagaimana cara memilih sertifikasi yang tepat sesuai dengan karier Anda. Sertifikasi tidak hanya memberikan pengetahuan teknis, tetapi juga membuktikan komitmen Anda terhadap pengembangan profesional berkelanjutan.',
                'penulis' => 'Dr. Sarah Wijaya, M.Kom',
                'jenis_konten' => 'Blog',
                'featured' => true,
                'views' => rand(500, 2000),
            ],
            [
                'judul' => 'Tren Teknologi 2025: AI, Blockchain, dan Quantum Computing',
                'konten' => 'Tahun 2025 membawa berbagai inovasi teknologi yang mengubah landscape industri IT. Dari AI generatif yang semakin canggih, blockchain yang mulai diadopsi secara mainstream, hingga quantum computing yang mulai menunjukkan potensinya. Profesional IT perlu memahami tren-tren ini untuk tetap relevan dan kompetitif di pasar kerja yang semakin dinamis.',
                'penulis' => 'Ahmad Rizki, CTO TechCorp',
                'jenis_konten' => 'Blog',
                'featured' => true,
                'views' => rand(800, 3000),
            ],
            [
                'judul' => 'Strategi Membangun Personal Branding untuk Profesional Muda',
                'konten' => 'Personal branding bukan lagi optional di dunia kerja modern. Di era LinkedIn dan media sosial, bagaimana Anda membangun citra profesional yang kuat? Artikel ini memberikan panduan lengkap mulai dari mengidentifikasi unique value proposition, konsistensi messaging, hingga networking strategis yang dapat meningkatkan visibility dan kesempatan karier Anda.',
                'penulis' => 'Lisa Handayani, Career Coach',
                'jenis_konten' => 'Blog',
                'featured' => true,
                'views' => rand(600, 2500),
            ],
            [
                'judul' => 'Work-Life Balance: Kunci Produktivitas Jangka Panjang',
                'konten' => 'Menjaga keseimbangan antara kehidupan pribadi dan profesional bukanlah hal yang mudah, namun sangat penting untuk kesuksesan jangka panjang. Burnout dapat menghambat produktivitas dan kreativitas. Temukan strategi efektif untuk mencapai work-life balance yang ideal, termasuk time management, setting boundaries, dan self-care routines.',
                'penulis' => 'Dr. Rudi Santoso, Psikolog Industri',
                'jenis_konten' => 'Blog',
                'featured' => false,
                'views' => rand(400, 1500),
            ],
            [
                'judul' => 'Mengoptimalkan Produktivitas dengan Tools Digital Terkini',
                'konten' => 'Berbagai tools digital dapat membantu meningkatkan produktivitas kerja secara signifikan. Dari project management tools seperti Asana dan Monday.com, communication tools seperti Slack dan Microsoft Teams, hingga automation tools seperti Zapier. Artikel ini mengulas tools-tools terbaik untuk berbagai kebutuhan workflow modern.',
                'penulis' => 'Maya Kusuma, Productivity Expert',
                'jenis_konten' => 'Blog',
                'featured' => false,
                'views' => rand(350, 1200),
            ],
            [
                'judul' => 'Soft Skills yang Paling Dicari Employer di 2025',
                'konten' => 'Selain technical skills, soft skills menjadi faktor penentu kesuksesan karier. Communication skills, emotional intelligence, critical thinking, dan adaptability menjadi yang paling dicari. Pelajari soft skills apa saja yang paling dicari employer dan bagaimana cara mengembangkannya melalui training dan pengalaman sehari-hari.',
                'penulis' => 'Dina Marlina, HR Director',
                'jenis_konten' => 'Blog',
                'featured' => false,
                'views' => rand(300, 1000),
            ],
            [
                'judul' => 'Remote Work: Tips Sukses Bekerja dari Rumah',
                'konten' => 'Remote work menjadi new normal di banyak perusahaan. Tantangannya adalah menjaga produktivitas dan work-life balance. Artikel ini memberikan tips praktis untuk tetap produktif dan engaged saat bekerja dari rumah, termasuk setup workspace yang ideal, routine harian, dan komunikasi efektif dengan tim.',
                'penulis' => 'Kevin Pratama, Remote Work Consultant',
                'jenis_konten' => 'Blog',
                'featured' => false,
                'views' => rand(450, 1800),
            ],
            [
                'judul' => 'Investasi Skill: Cara Cerdas Mengalokasikan Waktu untuk Belajar',
                'konten' => 'Belajar skill baru membutuhkan investasi waktu yang tepat. Dengan kesibukan pekerjaan sehari-hari, bagaimana cara mengalokasikan waktu belajar yang efektif? Temukan strategi efektif untuk mengalokasikan waktu belajar sambil tetap menjalankan pekerjaan, termasuk micro-learning, learning during commute, dan dedicated learning time.',
                'penulis' => 'Sari Dewi, Learning & Development Manager',
                'jenis_konten' => 'Blog',
                'featured' => false,
                'views' => rand(280, 900),
            ],
            [
                'judul' => 'Networking Profesional: Membangun Koneksi yang Bermakna',
                'konten' => 'Networking bukan sekedar mengumpulkan contact, tapi membangun relasi yang saling menguntungkan. Di era digital, networking dapat dilakukan melalui LinkedIn, meetup, dan conference. Pelajari cara networking yang efektif dan autentik, termasuk cara mengikuti up conversation, follow-up yang tepat, dan memberikan value sebelum meminta.',
                'penulis' => 'Andi Wijaya, Business Development Manager',
                'jenis_konten' => 'Blog',
                'featured' => false,
                'views' => rand(320, 1100),
            ],
            [
                'judul' => 'Mindset Growth: Kunci Menghadapi Tantangan Karier',
                'konten' => 'Growth mindset membantu profesional menghadapi tantangan dan kegagalan sebagai peluang belajar. Berbeda dengan fixed mindset yang menghindari tantangan, growth mindset melihat setiap kesulitan sebagai kesempatan untuk berkembang. Artikel ini membahas cara mengembangkan mindset yang tepat untuk kesuksesan karier jangka panjang.',
                'penulis' => 'Rina Sari, Leadership Coach',
                'jenis_konten' => 'Blog',
                'featured' => true,
                'views' => rand(550, 2200),
            ],
            [
                'judul' => 'Financial Planning untuk Professional Muda',
                'konten' => 'Mengelola keuangan sejak dini adalah kunci kebebasan finansial. Artikel ini membahas budgeting, investasi, emergency fund, dan retirement planning yang sesuai untuk professional muda. Termasuk tips praktis untuk mengalokasikan gaji pertama dan menghindari debt trap.',
                'penulis' => 'Budi Santoso, Financial Advisor',
                'jenis_konten' => 'Blog',
                'featured' => false,
                'views' => rand(380, 1300),
            ],
            [
                'judul' => 'Mental Health di Workplace: Pentingnya Self-Care',
                'konten' => 'Mental health increasingly menjadi concern di workplace modern. Stress, burnout, dan anxiety dapat mempengaruhi produktivitas dan kualitas hidup. Pelajari cara mengenali tanda-tanda masalah mental health dan strategi self-care yang efektif untuk menjaga keseimbangan psikologis.',
                'penulis' => 'Dr. Maya Putri, Clinical Psychologist',
                'jenis_konten' => 'Blog',
                'featured' => false,
                'views' => rand(420, 1600),
            ],
            [
                'judul' => 'Entrepreneurship vs Employment: Mana yang Tepat untuk Anda?',
                'konten' => 'Banyak profesional bingung antara melanjutkan karier sebagai employee atau memulai bisnis sendiri. Artikel ini menganalisis kelebihan dan kekurangan kedua pilihan, termasuk risk assessment, skill requirements, dan personality fit yang diperlukan untuk masing-masing jalur.',
                'penulis' => 'Rizky Ramadhan, Serial Entrepreneur',
                'jenis_konten' => 'Blog',
                'featured' => false,
                'views' => rand(360, 1400),
            ],
            [
                'judul' => 'Diversity & Inclusion: Membangun Workplace yang Inklusif',
                'konten' => 'Diversity dan inclusion bukan hanya tentang compliance, tapi juga tentang menciptakan workplace yang inovatif dan produktif. Pelajari cara membangun budaya inklusif, mengatasi unconscious bias, dan memanfaatkan diversity sebagai competitive advantage.',
                'penulis' => 'Citra Ayu, DEI Consultant',
                'jenis_konten' => 'Blog',
                'featured' => false,
                'views' => rand(290, 950),
            ],
            [
                'judul' => 'Future of Work: Bagaimana Teknologi Mengubah Cara Kita Bekerja',
                'konten' => 'Teknologi seperti AI, automation, dan platform collaboration mengubah fundamental cara kita bekerja. Artikel ini menganalisis tren future of work dan bagaimana profesional dapat mempersiapkan diri menghadapi perubahan yang increasingly cepat dan disruptive.',
                'penulis' => 'Fajar Nugroho, Future Work Researcher',
                'jenis_konten' => 'Blog',
                'featured' => true,
                'views' => rand(650, 2800),
            ],

            // Tutorial Category - Technical Skills & Professional Development (20 items)
            [
                'judul' => 'Tutorial Lengkap Digital Marketing untuk Pemula',
                'konten' => 'Panduan step-by-step untuk memulai karier di digital marketing. Dari dasar-dasar SEO, social media marketing, hingga email marketing, semua dibahas secara detail dan mudah dipahami. Termasuk tools gratis yang bisa digunakan, case study real, dan tips praktis untuk mendapatkan klien pertama.',
                'penulis' => 'Marketer Pro Academy',
                'jenis_konten' => 'Tutorial',
                'featured' => true,
                'views' => rand(800, 3500),
            ],
            [
                'judul' => 'Cara Membuat Website Profesional dengan WordPress (2025 Update)',
                'konten' => 'Tutorial lengkap membuat website profesional menggunakan WordPress dari nol hingga online. Termasuk pemilihan hosting, domain, theme premium, plugin essential, dan optimasi SEO terbaru 2025. Juga mencakup security hardening dan performance optimization untuk website enterprise-grade.',
                'penulis' => 'Web Developer Expert',
                'jenis_konten' => 'Tutorial',
                'featured' => false,
                'views' => rand(600, 2500),
            ],
            [
                'judul' => 'Menguasai Excel untuk Analisis Data Bisnis (Advanced)',
                'konten' => 'Panduan komprehensif menggunakan Microsoft Excel untuk analisis data bisnis. Dari fungsi dasar hingga pivot table, power query, data visualization dengan chart, dan macro automation. Termasuk template bisnis siap pakai dan shortcut keyboard untuk meningkatkan produktivitas.',
                'penulis' => 'Data Analyst Professional',
                'jenis_konten' => 'Tutorial',
                'featured' => false,
                'views' => rand(500, 2000),
            ],
            [
                'judul' => 'Tutorial Python untuk Data Science - Complete Course',
                'konten' => 'Belajar Python dari dasar untuk keperluan data science. Termasuk library pandas, numpy, matplotlib, seaborn, dan scikit-learn dengan contoh praktis. Tutorial ini mencakup preprocessing data, exploratory data analysis, machine learning algorithms, dan deployment model ke production.',
                'penulis' => 'Python Expert & Data Scientist',
                'jenis_konten' => 'Tutorial',
                'featured' => true,
                'views' => rand(1200, 5000),
            ],
            [
                'judul' => 'Panduan Lengkap Google Ads untuk Bisnis Online 2025',
                'konten' => 'Tutorial step-by-step membuat dan mengoptimalkan kampanye Google Ads. Dari riset keyword hingga analisis ROI dan optimasi budget. Mencakup Google Ads terbaru features seperti Performance Max, Discovery campaigns, dan AI-powered bidding strategies.',
                'penulis' => 'PPC Specialist & Google Ads Expert',
                'jenis_konten' => 'Tutorial',
                'featured' => false,
                'views' => rand(450, 1800),
            ],
            [
                'judul' => 'Cara Membuat Desain Grafis dengan Canva Pro + Adobe Suite',
                'konten' => 'Tutorial lengkap menggunakan Canva Pro untuk membuat desain grafis profesional. Dari social media post hingga presentasi bisnis. Juga mencakup integrasi dengan Adobe Creative Suite untuk workflow yang lebih advanced dan professional-grade output.',
                'penulis' => 'Design Guru & Creative Director',
                'jenis_konten' => 'Tutorial',
                'featured' => false,
                'views' => rand(400, 1600),
            ],
            [
                'judul' => 'Memulai Karier sebagai Content Creator di Era TikTok',
                'konten' => 'Panduan praktis memulai karier sebagai content creator. Dari content planning, video editing dengan CapCut dan Adobe Premiere, hingga monetisasi konten di berbagai platform. Termasuk algorithm hacking, trending sound usage, dan collaboration strategies.',
                'penulis' => 'Content Master & TikTok Influencer',
                'jenis_konten' => 'Tutorial',
                'featured' => false,
                'views' => rand(700, 2800),
            ],
            [
                'judul' => 'Tutorial Cyber Security untuk Pemula - Ethical Hacking',
                'konten' => 'Dasar-dasar cyber security yang wajib dipahami setiap profesional IT. Dari network security hingga ethical hacking basics. Mencakup tools seperti Kali Linux, Wireshark, Metasploit, dan Burp Suite. Juga membahas vulnerability assessment dan penetration testing methodology.',
                'penulis' => 'Security Expert & Ethical Hacker',
                'jenis_konten' => 'Tutorial',
                'featured' => false,
                'views' => rand(550, 2200),
            ],
            [
                'judul' => 'Belajar UI/UX Design dari Nol - Complete Guide 2025',
                'konten' => 'Tutorial komprehensif belajar UI/UX design untuk pemula. Termasuk design thinking, user research methods, wireframing, prototyping dengan Figma, dan usability testing. Mencakup design systems, accessibility guidelines, dan portfolio building untuk mendapatkan pekerjaan pertama.',
                'penulis' => 'UX Designer & Design Lead',
                'jenis_konten' => 'Tutorial',
                'featured' => false,
                'views' => rand(650, 2600),
            ],
            [
                'judul' => 'Panduan Project Management dengan Agile & Scrum 2025',
                'konten' => 'Tutorial lengkap implementasi Agile methodology dalam project management. Dari Scrum framework hingga tools seperti Jira, Azure DevOps, dan Trello. Mencakup advanced topics seperti SAFe, LeSS, dan agile scaling untuk enterprise environments.',
                'penulis' => 'Project Manager & Agile Coach',
                'jenis_konten' => 'Tutorial',
                'featured' => false,
                'views' => rand(480, 1900),
            ],
            [
                'judul' => 'Full Stack Web Development dengan MERN Stack',
                'konten' => 'Tutorial lengkap pengembangan web full-stack menggunakan MERN Stack (MongoDB, Express.js, React, Node.js). Dari setup development environment hingga deployment ke production. Mencakup authentication, real-time features, dan best practices untuk scalable applications.',
                'penulis' => 'Full Stack Developer & Tech Lead',
                'jenis_konten' => 'Tutorial',
                'featured' => true,
                'views' => rand(900, 3800),
            ],
            [
                'judul' => 'Machine Learning dengan TensorFlow & Python',
                'konten' => 'Tutorial mendalam machine learning menggunakan TensorFlow dan Python. Mencakup neural networks, deep learning, computer vision dengan CNN, dan NLP dengan transformers. Termasuk deployment model ke cloud dan MLOps practices.',
                'penulis' => 'ML Engineer & AI Researcher',
                'jenis_konten' => 'Tutorial',
                'featured' => false,
                'views' => rand(580, 2300),
            ],
            [
                'judul' => 'DevOps Engineering - Docker, Kubernetes & AWS',
                'konten' => 'Tutorial lengkap DevOps engineering dari development hingga production. Mencakup containerization dengan Docker, orchestration dengan Kubernetes, CI/CD pipelines, infrastructure as code dengan Terraform, dan cloud deployment di AWS.',
                'penulis' => 'DevOps Engineer & Cloud Architect',
                'jenis_konten' => 'Tutorial',
                'featured' => false,
                'views' => rand(620, 2500),
            ],
            [
                'judul' => 'Mobile App Development dengan Flutter - Advanced',
                'konten' => 'Tutorial advanced Flutter development untuk membuat aplikasi mobile cross-platform. Mencakup state management dengan Riverpod, advanced animations, platform-specific integrations, offline capabilities, dan publishing ke app stores.',
                'penulis' => 'Mobile Developer & Flutter Expert',
                'jenis_konten' => 'Tutorial',
                'featured' => false,
                'views' => rand(520, 2100),
            ],
            [
                'judul' => 'Blockchain Development dengan Solidity & Web3',
                'konten' => 'Tutorial pengembangan aplikasi blockchain menggunakan Solidity dan Web3.js. Mencakup smart contract development, DeFi protocols, NFT creation, dan dApp development. Termasuk testing dan deployment ke mainnet.',
                'penulis' => 'Blockchain Developer & Crypto Expert',
                'jenis_konten' => 'Tutorial',
                'featured' => false,
                'views' => rand(450, 1800),
            ],
            [
                'judul' => 'Cloud Computing dengan Microsoft Azure',
                'konten' => 'Tutorial komprehensif cloud computing menggunakan Microsoft Azure. Mencakup virtual machines, app services, databases, AI/ML services, DevOps, dan security. Termasuk certification preparation dan real-world project implementation.',
                'penulis' => 'Cloud Architect & Azure Expert',
                'jenis_konten' => 'Tutorial',
                'featured' => false,
                'views' => rand(490, 2000),
            ],
            [
                'judul' => 'Quality Assurance & Software Testing Automation',
                'konten' => 'Tutorial lengkap QA engineering dan automated testing. Mencakup manual testing, Selenium WebDriver, API testing dengan Postman, performance testing dengan JMeter, dan test automation frameworks. Termasuk CI/CD integration dan best practices.',
                'penulis' => 'QA Engineer & Test Automation Lead',
                'jenis_konten' => 'Tutorial',
                'featured' => false,
                'views' => rand(430, 1700),
            ],
            [
                'judul' => 'E-Commerce Development dengan Shopify & WooCommerce',
                'konten' => 'Tutorial membangun toko online professional dengan Shopify dan WooCommerce. Mencakup theme customization, payment integration, inventory management, marketing automation, dan analytics. Termasuk dropshipping setup dan marketplace integration.',
                'penulis' => 'E-Commerce Developer & Business Owner',
                'jenis_konten' => 'Tutorial',
                'featured' => false,
                'views' => rand(550, 2200),
            ],
            [
                'judul' => 'Game Development dengan Unity - Complete Course',
                'konten' => 'Tutorial lengkap pengembangan game menggunakan Unity engine. Mencakup C# programming, 2D/3D game development, physics, animation, UI systems, multiplayer, dan publishing ke berbagai platform. Termasuk monetization strategies dan game marketing.',
                'penulis' => 'Game Developer & Unity Expert',
                'jenis_konten' => 'Tutorial',
                'featured' => false,
                'views' => rand(680, 2700),
            ],
            [
                'judul' => 'IoT Development dengan Arduino & Raspberry Pi',
                'konten' => 'Tutorial Internet of Things development menggunakan Arduino dan Raspberry Pi. Mencakup sensor integration, wireless communication, cloud connectivity, data visualization, dan real-world IoT project implementation untuk smart home dan industry applications.',
                'penulis' => 'IoT Engineer & Hardware Specialist',
                'jenis_konten' => 'Tutorial',
                'featured' => false,
                'views' => rand(410, 1600),
            ],

            // News Category - Industry Updates & Career Trends (20 items)
            [
                'judul' => 'Indonesia Masuk Top 10 Negara dengan Pertumbuhan Startup Tercepat 2025',
                'konten' => 'Menurut laporan terbaru dari Google dan Temasek, Indonesia menduduki peringkat ke-8 dalam daftar negara dengan pertumbuhan startup tercepat di dunia. Dengan total 2.300+ startup aktif, Indonesia menunjukkan potensi besar di bidang fintech, e-commerce, dan edtech. Unicorn baru seperti GoTo dan Traveloka terus berkembang pesat.',
                'penulis' => 'Startup Indonesia News',
                'jenis_konten' => 'News',
                'featured' => true,
                'views' => rand(1500, 6000),
            ],
            [
                'judul' => 'Kemenaker RI Luncurkan Program Sertifikasi Digital untuk 1 Juta Pekerja',
                'konten' => 'Kementerian Ketenagakerjaan RI meluncurkan program sertifikasi digital massive untuk meningkatkan kompetensi 1 juta pekerja di sektor teknologi. Program ini bekerja sama dengan BNSP dan platform digital learning terkemuka. Fokus utama pada skill digital seperti programming, data analytics, dan cyber security.',
                'penulis' => 'Kemenaker News',
                'jenis_konten' => 'News',
                'featured' => false,
                'views' => rand(800, 3200),
            ],
            [
                'judul' => 'Gaji Programmer Indonesia Naik 25% di Tengah Krisis Global',
                'konten' => 'Survei terbaru dari Stack Overflow menunjukkan gaji programmer Indonesia meningkat 25% dalam 2 tahun terakhir. Rata-rata gaji senior developer mencapai Rp 25 juta per bulan. Permintaan tinggi untuk skill seperti React, Python, dan cloud computing mendorong kenaikan ini.',
                'penulis' => 'Tech Salary Report',
                'jenis_konten' => 'News',
                'featured' => false,
                'views' => rand(1200, 4800),
            ],
            [
                'judul' => 'Microsoft Buka 500 Lowongan Kerja di Indonesia Tahun 2025',
                'konten' => 'Microsoft Indonesia mengumumkan pembukaan 500+ lowongan kerja untuk berbagai posisi teknologi. Fokus pada cloud computing, AI, dan cyber security. Program Microsoft Learn for Careers menargetkan 10.000 talenta digital Indonesia dalam 3 tahun ke depan.',
                'penulis' => 'Corporate News Desk',
                'jenis_konten' => 'News',
                'featured' => false,
                'views' => rand(900, 3600),
            ],
            [
                'judul' => 'BNSP Luncurkan 15 Sertifikasi Baru untuk Industri 4.0',
                'konten' => 'Badan Nasional Sertifikasi Profesi (BNSP) meluncurkan 15 sertifikasi baru yang fokus pada Industri 4.0. Termasuk sertifikasi untuk AI Engineer, IoT Specialist, dan Digital Manufacturing. Program ini didukung oleh Kemenperin dan asosiasi industri nasional.',
                'penulis' => 'BNSP Official',
                'jenis_konten' => 'News',
                'featured' => false,
                'views' => rand(600, 2400),
            ],
            [
                'judul' => 'Universitas Indonesia Jadi Pusat Riset AI Terdepan di Asia Tenggara',
                'konten' => 'Universitas Indonesia mendapat pendanaan Rp 500 miliar dari Kemendikbudristek untuk membangun pusat riset AI terdepan di Asia Tenggara. Program ini akan melibatkan 200+ peneliti dan menghasilkan 50+ inovasi AI untuk industri nasional dalam 5 tahun ke depan.',
                'penulis' => 'Education News Network',
                'jenis_konten' => 'News',
                'featured' => false,
                'views' => rand(700, 2800),
            ],
            [
                'judul' => 'GoTo Group Investasi Rp 2 Triliun untuk Digital Talent Development',
                'konten' => 'GoTo Group mengumumkan investasi Rp 2 triliun untuk pengembangan talenta digital Indonesia. Program ini mencakup bootcamp programming, sertifikasi cloud, dan partnership dengan 50+ universitas. Target: 100.000 developer terampil dalam 3 tahun.',
                'penulis' => 'Fintech News Indonesia',
                'jenis_konten' => 'News',
                'featured' => false,
                'views' => rand(850, 3400),
            ],
            [
                'judul' => 'Indonesia Butuh 600.000 Developer dalam 5 Tahun ke Depan',
                'konten' => 'Menurut kajian Kemenkominfo, Indonesia membutuhkan 600.000 developer qualified dalam 5 tahun ke depan untuk mendukung transformasi digital nasional. Gap skill saat ini mencapai 400.000 developer. Program coding bootcamp dan vocational training dipercepat.',
                'penulis' => 'Digital Economy Report',
                'jenis_konten' => 'News',
                'featured' => false,
                'views' => rand(950, 3800),
            ],
            [
                'judul' => 'Tokopedia Buka Academy untuk 10.000 UMKM Digital',
                'konten' => 'Tokopedia meluncurkan Tokopedia Academy untuk melatih 10.000 UMKM dalam transformasi digital. Program ini mencakup e-commerce fundamentals, digital marketing, dan marketplace optimization. Kolaborasi dengan Kemenkop UKM dan asosiasi pedagang.',
                'penulis' => 'E-Commerce News',
                'jenis_konten' => 'News',
                'featured' => false,
                'views' => rand(650, 2600),
            ],
            [
                'judul' => 'Remote Work Tetap Dominan di Industri Tech Indonesia',
                'konten' => 'Survei terbaru menunjukkan 70% perusahaan tech Indonesia menerapkan hybrid working model. Remote work tetap menjadi preferensi utama untuk developer dan designer. Tools seperti Slack, Zoom, dan Notion menjadi standar baru dalam workplace digital.',
                'penulis' => 'Workplace Trends',
                'jenis_konten' => 'News',
                'featured' => false,
                'views' => rand(780, 3100),
            ],
            [
                'judul' => 'Shopee PayLater Luncurkan Program Fintech Education',
                'konten' => 'Shopee PayLater bekerja sama dengan OJK meluncurkan program edukasi fintech untuk 1 juta pengguna. Program ini mencakup literasi keuangan digital, investasi online, dan financial planning. Fokus pada generasi Z dan milenial yang aktif di platform e-commerce.',
                'penulis' => 'Fintech Education Initiative',
                'jenis_konten' => 'News',
                'featured' => false,
                'views' => rand(550, 2200),
            ],
            [
                'judul' => 'Bank Indonesia Percepat Implementasi QRIS untuk UMKM',
                'konten' => 'Bank Indonesia mempercepat adopsi QRIS untuk 30 juta UMKM di seluruh Indonesia. Program ini didukung oleh fintech payment seperti GoPay, OVO, dan Dana. Target: 50% transaksi digital menggunakan QRIS dalam 2 tahun ke depan.',
                'penulis' => 'Bank Indonesia News',
                'jenis_konten' => 'News',
                'featured' => false,
                'views' => rand(620, 2500),
            ],
            [
                'judul' => 'Kampus Merdeka Sukses Luluskan 500.000 Mahasiswa Bersertifikat',
                'konten' => 'Program Kampus Merdeka berhasil meluluskan 500.000 mahasiswa dengan sertifikasi kompetensi. Kolaborasi dengan 1.200+ perusahaan menghasilkan 80% mahasiswa mendapat pekerjaan dalam 6 bulan. Program magang dan proyek kemanusiaan menjadi highlight.',
                'penulis' => 'Kampus Merdeka Update',
                'jenis_konten' => 'News',
                'featured' => false,
                'views' => rand(720, 2900),
            ],
            [
                'judul' => 'Indonesia Jadi Tuan Rumah World Blockchain Summit 2025',
                'konten' => 'Indonesia terpilih sebagai tuan rumah World Blockchain Summit 2025. Event ini akan dihadiri 5.000+ peserta dari 50 negara. Fokus pada regulasi crypto, DeFi development, dan blockchain adoption untuk pemerintah dan korporasi.',
                'penulis' => 'Blockchain News Global',
                'jenis_konten' => 'News',
                'featured' => false,
                'views' => rand(580, 2300),
            ],
            [
                'judul' => 'Grab Indonesia Investasi Rp 1 Triliun untuk EV Ecosystem',
                'konten' => 'Grab Indonesia mengumumkan investasi Rp 1 triliun untuk pengembangan ekosistem kendaraan listrik. Program ini mencakup 10.000 unit EV untuk driver partner, charging station network, dan training program untuk teknisi EV. Kolaborasi dengan pabrikan nasional.',
                'penulis' => 'Green Tech News',
                'jenis_konten' => 'News',
                'featured' => false,
                'views' => rand(690, 2700),
            ],
            [
                'judul' => 'Telkom University Jadi Center of Excellence untuk 5G Technology',
                'konten' => 'Telkom University ditunjuk sebagai Center of Excellence untuk 5G Technology oleh Kemendikbudristek. Program ini mendapat dukungan dari Telkomsel dan Ericsson. Fokus pada riset 5G applications, IoT, dan smart city solutions untuk Indonesia.',
                'penulis' => 'Telco News Indonesia',
                'jenis_konten' => 'News',
                'featured' => false,
                'views' => rand(540, 2100),
            ],
            [
                'judul' => 'Startup Edtech Indonesia Raih Pendanaan Rp 5 Triliun',
                'konten' => 'Sektor edtech Indonesia mendapat pendanaan Rp 5 triliun dalam 6 bulan terakhir. Unicorn baru seperti Ruangguru dan Sekolah.mu menunjukkan potensi besar. Fokus pada personalized learning, gamification, dan vocational training untuk industry 4.0.',
                'penulis' => 'Edtech Investment Report',
                'jenis_konten' => 'News',
                'featured' => false,
                'views' => rand(630, 2500),
            ],
            [
                'judul' => 'Kemenperin Luncurkan Program Digital Manufacturing untuk 1000 Industri',
                'konten' => 'Kementerian Perindustrian meluncurkan program digital manufacturing untuk 1.000 perusahaan manufaktur. Program ini mencakup implementasi Industry 4.0, automation, dan digital twin. Kolaborasi dengan Siemens, Schneider Electric, dan industri nasional.',
                'penulis' => 'Manufacturing News',
                'jenis_konten' => 'News',
                'featured' => false,
                'views' => rand(510, 2000),
            ],
            [
                'judul' => 'Indonesia Targetkan 10 Juta Developer Digital pada 2030',
                'konten' => 'Pemerintah Indonesia menargetkan 10 juta developer digital pada 2030 untuk mendukung visi Indonesia Emas. Program ini mencakup pengembangan 1.000 coding school, sertifikasi massal, dan partnership dengan tech giants seperti Google, Microsoft, dan Amazon.',
                'penulis' => 'Digital Indonesia 2030',
                'jenis_konten' => 'News',
                'featured' => false,
                'views' => rand(880, 3500),
            ],
            [
                'judul' => 'Cyber Security Menjadi Prioritas Utama Perusahaan Indonesia',
                'konten' => 'Survei terbaru menunjukkan 85% perusahaan Indonesia meningkatkan budget cyber security sebesar 40% dalam 2 tahun. Ancaman ransomware dan data breach mendorong investasi pada security tools dan training. Sertifikasi CEH dan CISSP menjadi mandatory.',
                'penulis' => 'Cyber Security Report',
                'jenis_konten' => 'News',
                'featured' => false,
                'views' => rand(670, 2700),
            ],
        ];

        foreach ($blogEntries as $data) {
            Blog::create([
                'nama_artikel'      => $data['judul'],
                'jenis_konten'      => $data['jenis_konten'],
                'deskripsi'         => Str::limit(strip_tags($data['konten']), 150),
                'thumbnail'         => null,
                'konten'            => $data['konten'],
                'status'            => 'Publish',
                'penulis'           => $data['penulis'],
                'views'             => $data['views'],
                'featured'          => $data['featured'],
                'meta_title'        => $data['judul'],
                'meta_description'  => Str::limit(strip_tags($data['konten']), 160),
                'slug'              => Str::slug($data['judul']),
                'created_at'        => now()->subDays(rand(1, 30)),
                'updated_at'        => now()->subDays(rand(1, 30)),
            ]);
        }
    }
}
